name: CI

on:
  pull_request_target:
  push:
    branches:
    - main
  workflow_dispatch:


env:
  # Check Only Changed Modules
  # If true, only changed modules will be analyzed.
  # If false, all discovered modules will be analyzed.
  check_only_changed: ${{ github.event_name == 'pull_request_target' }}
  REF: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.ref || github.ref }}
  REPO: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name || github.repository }}

permissions:
  contents: read
  checks: read

jobs:
  discover_modules:
    name: "Discover Go Modules"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    env:
      DIR: ${{ github.workspace }}
    steps:
      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: ${{ env.REPO }}
          ref: ${{ env.REF }}
      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version-file: 'kubernetes/controller/go.mod'
      - name: run resource controller test
        run: cd kubernetes/controller && task test
